### ISSUE TITLE
[User interface] Toolbars can be moved offscreen

### ISSUE THREAD

**Issue by NotLe0n** [ScalarVector1/DragonLens#14]
The toolbars can be moved offscreen, making it impossible access some tools and move the it again.
![image](https://user-images.githubusercontent.com/26361108/217626473-891186d7-eb8f-4c75-ae9f-fca9c151b51c.png)

**Comment by ScalarVector1** [comment]
Fixed in https://github.com/ScalarVector1/DragonLens/commit/62a277bb00c6d4e953bd9043ec5d942264999ac2
