### ISSUE TITLE
[Tool] Blank Entries in Some Spawner Tools

### ISSUE THREAD

**Issue by Antirhinnum** [ScalarVector1/DragonLens#18]
Already reported on Discord, at least.

Some spawner tools have blank entries that do nothing on click.

No errors in logs, no other mods enabled.

Known cases:
 - Buff spawner. [This line](https://github.com/ScalarVector1/DragonLens/blob/4aa00c81fb33f29eb36e9a6dbc50ce1d19926709/Content/Tools/Spawners/BuffSpawner.cs#L72) appears to be the issue, as there is no Buff 0.
 - NPC spawner. Same issue as the buff spawner.
 - Projectile spawner. Same issue as above.
 - Item spawner. Also has a None (0) ID, but additionally has a few dozen extra entries -- likely due to `ItemID.Sets.Deprecated`?

**Comment by ScalarVector1** [comment]
Is there any valid use case for wanting to see these? I highly doubt any user would ever have any need to spawn these items -- if they even behave properly at all

**Comment by steviegt6** [comment]
First Fractal, @ScalarVector1.
