### ISSUE TITLE
Guys, why isn’t my tModLoader opening 

### ISSUE THREAD

**Issue by aeterna-gh** [ScalarVector1/DragonLens#35]
When I play t mod loader all it is is black screen and no terera I have this mod instal ed and it do sent work please help me I haven been able to play t mod loder for 3 days and want to play Teresa please and thank you

**Comment by ScalarVector1** [comment]
This issue would better be reported to https://github.com/tModLoader/tModLoader

**Comment by aeterna-gh** [comment]
but I ask ed there and they did not give me good answer please I need to play terreria with my friend
