### ISSUE TITLE
Clicking on the remove button activates the tool before removing

### ISSUE THREAD

**Issue by Jadams505** [ScalarVector1/DragonLens#53]
### Description
When clicking the remove button on a tool it activates the tool before removing. This was not the behavior prior to the latest `1.3.2` update

### Steps to reproduce
1. Open up the customize tool (to allow the ability to remove tools)
2. Click on the red "remove tool" button on any tool in any toolbar
3. This will trigger the tool (unintended) and remove the tool from the toolbar (intended)

https://user-images.githubusercontent.com/56134537/227739730-6e90c1b2-6311-453c-90ea-cedabac4ebde.mp4

### Expected behavior
Remove the tool from the toolbar without activating the tool

### Actual behavior
The tool is removed, but the tool activates before being removed

**Comment by ScalarVector1** [comment]
Should be fixed in next update
