### ISSUE TITLE
[1.4.4] Tile Painter Freezes Upon Selecting Second Point

### ISSUE THREAD

**Issue by Antirhinnum** [ScalarVector1/DragonLens#54]
[client.log](https://github.com/ScalarVector1/DragonLens/files/11117812/client.log)

Reproduction:
1. Enter any world with any character, then open the Tile Painter tool.
2. Select any point.
3. Select any other point.

The game freezes, as the error happens every single frame after selecting the second point.

**Comment by ScalarVector1** [comment]
Should be fixed in next update
