### ISSUE TITLE
[tml-stable; Bug] Can`t return journey mode from world

### ISSUE THREAD

**Issue by WitherTaco** [ScalarVector1/DragonLens#55]
I found a bug where if you press the difficulty switcher button in the journey mode world, then the world ceases to be this mode and the journey mode character will not be able to enter this world
Dragon Lens v1.3.2
tml 1.4-stable (and can be in 1.4.4, however, I did not check)

**Comment by Cyrillya** [comment]
If any devs notice this, I suggest turning off journey mode restrictions as a feature of this mod

**Comment by ScalarVector1** [comment]
Should be fixed in next update
