### ISSUE TITLE
Make "Advanced Layout" provide everything + Add Tile Remover

### ISSUE THREAD

**Issue by Setnour6** [ScalarVector1/DragonLens#57]
This issue leans towards a feature request.
Using Windows 11, Steam, Latest 1.4.4 version

## Issue 1 "Advanced Layout" Description
Clicking on the Advanced Layout button in the Layout Presets UI does not present the following options:
- Clear Buffs
- Shader Tool
The problem is with the Clear Buffs option.

See the below screenshot:
![image](https://user-images.githubusercontent.com/70764728/235465018-41ba192b-7e16-48a3-a449-81312512f846.png)

The "Clear Buffs" option could be on the right of the screen where the rest of the removal functions/options are.

## Issue 2 "Tile Remover" Description
There is only an option for adding tiles via the "Tile Spawner". There are some tiles that cannot be removed through normal means, or if a tile cannot be destroyed by a pickaxe of any level. I would like to see a "Tile Remover" option added as well (unless Tile Painter does the same thing)

I have yet to see whether Tile Painter also copies the air (or if there is a toggle for copying it). The game freezes anyways.

There could be a toggle that tells you to "remove tiles" and it would function the same way as placing a selected tile, but you are instead erasing the tile.

**Comment by ScalarVector1** [comment]
Tile painter will copy air and works for the purpose, though I could see the application for a simple 'tile zapper'. I do wonder if adding an 'air' option to the tile spawner may fill this use though without an entire new tool?

**Comment by ScalarVector1** [comment]
> Example: you have two houses seperated from each other and you want to copy and paste them into a cave. The toggle could be set to 'off' and that would make it so the dirt walls in the cave (if you paste there) will not be affected by also pasting the air.

Null tiles in StructureHelper cover this use case, though that ofcourse requires the installation of StructureHelper to be able to place down

**Comment by Setnour6** [comment]
> > Example: you have two houses seperated from each other and you want to copy and paste them into a cave. The toggle could be set to 'off' and that would make it so the dirt walls in the cave (if you paste there) will not be affected by also pasting the air.
> 
> Null tiles in StructureHelper cover this use case, though that ofcourse requires the installation of StructureHelper to be able to place down

I was going to say that you could add the tiles from StructureHelper to DragonLens. There will be two tiles that do the exact same thing though. I could try to enable StructureHelper and see what I can do in this scenario

**Comment by Setnour6** [comment]
Hello, it's been almost two months. Issue 1 is still prominent, given that when I loaded the latest workshop version of DragonLens, the Buff Despawner and newly added Sound Player tools do not appear at all.
Right now, the advanced layout looks like this:
![image](https://github.com/ScalarVector1/DragonLens/assets/70764728/dc283385-7146-4c2f-8bbd-d96268de6d67)

If I recall, the toolbars at the bottom should also be spaced out.

**Comment by ScalarVector1** [comment]
You likely need to clear out your old saved layout directory. Deleting the tModLoader/DragonLensLayouts directory should ensure new layouts are generated properly.

**Comment by Setnour6** [comment]
> You likely need to clear out your old saved layout directory. Deleting the tModLoader/DragonLensLayouts directory should ensure new layouts are generated properly.

I cleared the directories for both preview and non-preview builds of tModLoader. It works, so part of this issue is solved. I'll close this issue anyways since there hasn't been any activity for the tile remover part of this issue (I hadn't had the chance to test it)
