### ISSUE TITLE
[Bug] Clicking "NPC Spawner" causes the game to freeze.

### ISSUE THREAD

**Issue by Setnour6** [ScalarVector1/DragonLens#58]
Using Windows 11, Steam. Latest 1.4.4 Version

## Description

Clicking on the "NPC Spawner" button immediately stops the game and causes it to freeze. No crash seems to occur after.
This even causes client.log to reach 40.7 MB (42,716,598 bytes). I'm worried that this might have also caused a surge in memory use as well.

Mod List:
- HERO's Mod
- Cheat Sheet
- Everglow
- ExampleMod
- UwUMod (does nothing special, self-compiled)
- SuperDummyFromFargosMod (private mod, self-compiled)

## Reproduction

Step 1. Enter a world
Step 2. Open NPC Spawner
Step 3. The game freezes.

Expected behavior: The NPC Spawner loads all NPCs as normal.
Actual Behavior: The NPC Spawner fails to load any NPC and the game freezes.

**Comment by ScalarVector1** [comment]
Could I perhaps see a snippet of the log file? It may give a hint as to what is happening. I understand your hesitation to upload the entire thing given its apparent size.

**Comment by Setnour6** [comment]
I trimmed the log. The last error message keeps repeating over and over. 
[client.log](https://github.com/ScalarVector1/DragonLens/files/11374385/client.log)

I also tested this after disabling Everglow and the NPC spawner works fine. I do worry that other mods that utilize bestiary in any way might also cause the issue

**Comment by steviegt6** [comment]
Everglow is pretty unique, wouldn't be surprised if something they're doing interacts poorly with our systems; it's been recently open-sourced as free software [here](https://github.com/dfgasdfg/Everglow), so I'll have a look.

**Comment by ScalarVector1** [comment]
Interesting... I've never seen a mod with this structure before. I'm not sure how much we can do to account for this outside of a more extreme try/catch net? Is there a reason why everglow handles itself in this way? It seems very strange to me but ofcourse this is looking in as an outsider.

**Comment by Setnour6** [comment]
Sorry for being late, I forgot to provide an update earlier. The problem has been solved and the NPC Spawner works now via a hotfix.
I can't really provide a proper insight into the Everglow internal structure because even I do not understand it.
I'll let you know if I have any further questions here.
