### ISSUE TITLE
Add Infinite Flight toggle

### ISSUE THREAD

**Issue by Setnour6** [ScalarVector1/DragonLens#62]
### Do you plan on contributing to this feature?
Maybe

### Proposal Description

Just to be straightforward:

This issue proposes a toggle which allows for infinite flying.
Sure you have noclip, but what if you want to test wings, or move smoothly and fair (not wing time fair though) for testing boss fights and such, or you want to pretend that you have the soaring insignia item, but you don't have to go through the hassle of opening the item spawner to equip the insignia and taking up an accessory slot (or just to open the item spawner to get it).
One toggle does the trick.

### Alternative Approach

Incorporate this in the GodMode toggle by shift-clicking said toggle, and an extra icon or function will appear that makes it so you have infinite flight, similar to HERO's Mod/Cheat Sheet.

### Function

If you consider the normal approach, Left click enables infinite flight, right click enable infinite hover (for magic carpet and so on), and that's it. You can add a shift-click function to enable flight boosts for both left and right clicks. Of course, it can be done in any way if needed.

If you consider the alternative approach:
Left click: God mode.
Right click: Dog mode.
Shift Left Click: Enable Infinite Flight.
Shift Right Click: Enable Infinite Flight + Switch modes (or do nothing, or same as shift left click).
Of course, you can do anything you want with that.

**Comment by ScalarVector1** [comment]
I'm not sure I see a convincing use case for this while items such as the soaring insignia exist in vanilla. This could be used in combination with the accessory tray already to accomplish this goal. Is there a practical reason to want a tool over this?

**Comment by Setnour6** [comment]
> I'm not sure I see a convincing use case for this while items such as the soaring insignia exist in vanilla. This could be used in combination with the accessory tray already to accomplish this goal. Is there a practical reason to want a tool over this?

Going to click for the item spawner, click on soaring insignia, click on accessory tray, and then click on empty accessory slot in said tray could work, but that is four clicks. The infinite flight toggle only needs one click, while also pressing shift at the same time.
With no-clip, you move sharply through blocks, but infinite flight only boosts wing time and you can still move as you would with any form of flight.

To add to the infinite flight, perhaps right click can instead toggle infinite hovering (magic carpet forever) and shift click to toggle flight boosts instead. I just thought of that now.

**Comment by steviegt6** [comment]
> I'm not sure I see a convincing use case for this while items such as the soaring insignia exist in vanilla. This could be used in combination with the accessory tray already to accomplish this goal. Is there a practical reason to want a tool over this?

Mods like Calamity modify the behavior of the accessory.

**Comment by steviegt6** [comment]
Hijacking this slightly, but it holds some relevance; an expanded UI for God/Dog Mode that lets you enable/disable each infinite resource would be nice -- regular toggling would work as expected but power users should be able to toggle individually. Unsure of how this UI should be accessible. This is also useful when the time comes to add modded support through an API.

**Comment by MrRoomba69** [comment]
> > I'm not sure I see a convincing use case for this while items such as the soaring insignia exist in vanilla. This could be used in combination with the accessory tray already to accomplish this goal. Is there a practical reason to want a tool over this?
> 
> Mods like Calamity modify the behavior of the accessory.

i was going to say that before i read the entire thing

**Comment by Setnour6** [comment]
It's merged but hopefully, in the future, it can be relocated (or kept if you want) to its own toggle outside of the player editor or within godmode.
