### ISSUE TITLE
[Crash] System.Exception: The internal name of a mod cannot contain English periods

### ISSUE THREAD

**Issue by Phoupraw** [ScalarVector1/DragonLens#63]
The crash happens during mod loading.
[tModLoader-Logs.zip](https://github.com/ScalarVector1/DragonLens/files/11432679/tModLoader-Logs.zip)
> at Terraria.ModLoader.Core.ModOrganizer.VerifyNames(List\`1 mods) in tModLoader\Terraria\ModLoader\Core\ModOrganizer.cs:line 374
> at Terraria.ModLoader.Core.ModOrganizer.SelectAndSortMods(IEnumerable\`1 mods, CancellationToken token) in tModLoader\Terraria\ModLoader\Core\ModOrganizer.cs:line 312
> at Terraria.ModLoader.ModLoader.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModLoader.cs:line 118
> at Terraria.ModLoader.ModLoader.<>c__DisplayClass48_0.<BeginLoad>b__0() in tModLoader\Terraria\ModLoader\ModLoader.cs:line 105
> at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
> at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
> at System.Threading.ThreadPoolWorkQueue.Dispatch()
> at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

**Comment by steviegt6** [comment]
Did you build this yourself? Rename the folder from `DragonLens-dev-1.4.3-upstream-fixes` to `DraglonLens`.

**Comment by Phoupraw** [comment]
> Did you build this yourself? Rename the folder from `DragonLens-dev-1.4.3-upstream-fixes` to `DragonLens`.

Solved! Thank you.
