### ISSUE TITLE
the Quality of life mod breaks the player editor

### ISSUE THREAD

**Issue by eldritch-cookie** [ScalarVector1/DragonLens#67]
https://github.com/487666123/ImproveGame
the game crashes and makes intense clicking sounds when i use the player editor with the quality of life mod

**Comment by steviegt6** [comment]
Logs?

**Comment by eldritch-cookie** [comment]
here is it 
[client.log](https://github.com/ScalarVector1/DragonLens/files/11940896/client.log)
were you able to replicate my issue?

**Comment by Cyrillya** [comment]
This should be closed as it's already fixed
