### ISSUE TITLE
Item Spawner Frame Rate Drop Issue

### ISSUE THREAD

**Issue by JacksonWoodsknight** [ScalarVector1/DragonLens#88]
So, whenever I open the Item Spawner menu. For whatever reason the game's frame rate suddenly drops down to two frames per second. But then whenever I close the Item Spawner menu. The frame rate suddenly goes back up to the normal rate. I don't know the solid answer for this, but I can tell that this is caused from how the menu loads every single item icon at once. But maybe you can chat with the people behind the Magic Storage mod and ask of how they got around that or how it works so you can maybe ask to use that bit of code and implement it in DragonLens's Item Spawner menu, or maybe learn from how that code works and find out what makes it work better. I ain't sure of which is the best, I'm just throwing the suggestion out there.

**Comment by ScalarVector1** [comment]
this is false, item assets are preloaded asynchronously when the game starts. This is most likely due to a mod's item throwing an exception. You will need to find which mod and report this behavior to that mod's developers.
