### ISSUE TITLE
item spawner possibly corrupting characters 

### ISSUE THREAD

**Issue by clockworkMatrix** [ScalarVector1/DragonLens#98]
i was using the item spawner to test stuff, and kept getting back onto TML to find my saves corrupted (unknownerror).  I checked the log to see if it'd been a specific mod, and I found this
![image_2024-07-05_203125744](https://github.com/ScalarVector1/DragonLens/assets/174842733/4c071345-47cf-44ef-83ad-aeb1f58e2363)
(i couldn't find any of the system. files, things close to them but not quite) 
is there something specific i'm supposed to do/change? i'm no programming expert so it might not even be this. however the error only appeared to happen to characters i'd used the item spawner with, as i created a character and left/rejoined the world to see if it was still broken after trying a different troubleshooting method. worlds also dont appear to be affected

**Comment by ScalarVector1** [comment]
Unrelated, this is it failing to navigate to the wiki to pull up the help page.
